git config --global alias.a "add"
git config --global alias.b "branch"
git config --global alias.co "checkout"
git config --global alias.st "status"
git config --global alias.c "commit"
git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset' --abbrev-commit --date=relative"
git config --global alias.wslog "log --ignore-space-at-eol -p -w -b"
git config --global alias.wsdiff "diff --ignore-space-at-eol -w -b --no-ext-diff"
git config --global core.editor "gvim"
