" -------------------------------------
"  General settings
" -------------------------------------
execute pathogen#infect()

filetype indent on    "file type detection
filetype plugin on

set nocompatible

set autoread                " Set to auto read when a file is changed from
set ruler                   " Always show current position
set number
"set relativenumber

set ignorecase              " ignore case when searching
set hlsearch                " Highlight search results
set smartcase               " When searching try to be smart about cases
set incsearch

set showmatch               " Show matching brackets when text indicator is over them
set matchtime=3

set splitbelow
set splitright

inoremap } }<Left><c-o>%<c-o>:sleep 500m<CR><c-o>%<c-o>a
inoremap ] ]<Left><c-o>%<c-o>:sleep 500m<CR><c-o>%<c-o>a
inoremap ) )<Left><c-o>%<c-o>:sleep 500m<CR><c-o>%<c-o>a

set wildmode=list:longest,full

set showcmd
set list                    " show trailing whiteshace and tabsvi
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+,eol:¬
"
" No annoying sound on errors
set noerrorbells
set visualbell
set t_vb=
"set tm=500
set timeoutlen=1000 ttimeoutlen=0
set backupcopy=yes

set shortmess=a
set laststatus=2
set noshowmode
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix
" -------------------------------------
"  Text settings
" -------------------------------------

set autoindent              " automatic indent new lines
set binary
set noeol  "disable auto end of line

" -------------------------------------
"  File & backup settings
" -------------------------------------

set nobackup
set nowb
set noswapfile


" -------------------------------------
"  Appearance settings
" -------------------------------------

syntax enable                "basic syntax highlight

set foldmethod=indent
set nofoldenable
set foldlevel=0

"set background=dark
colorscheme dracula
set termguicolors
set t_Co=256
set timeout timeoutlen=1000 ttimeoutlen=0
let g:indentLine_setConceal = 0


set conceallevel=1


set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/node_modules/*,*/coverage/*,*/target/*     " Linux/MacOSX
source ~/dotfiles/vim/startup/keys.vim
source ~/dotfiles/vim/startup/plugins.vim
source ~/dotfiles/vim/startup/abbr.vim


set dictionary+=./.dictionary

"onmi func
augroup omnifuncs
	autocmd!
	autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
	autocmd FileType html setlocal omnifunc=htmlcomplete#CompleteTags
"	autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
	autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
augroup end

if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[1 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' |
    \   silent execute '!echo -ne "\e[5 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[3 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif
command! WipeReg for i in range(34,122) | silent! call setreg(nr2char(i), []) | endfor
