alias gitignore='cp ~/dotfiles/git/.gitignore .'
alias gitattributes='cp ~/dotfiles/git/.gitattributes .'
alias editorconfig='cp ~/dotfiles/editorconfig/.editorconfig .'
alias tern-project='cp ~/dotfiles/tern/tern-project.symlink ./.tern-project'
alias t='~/dotfiles/tmux/t.sh'
